In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

df = pd.read_csv("homeprices.csv")




In [3]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
model = linear_model.LinearRegression()

model.fit(df[['area']],df.price)

LinearRegression()

In [8]:
model.predict([[2600]])

array([533664.38356164])

In [10]:
model.score(df[['area']],df['price'])

0.9584301138199486

In [11]:
import pickle

In [13]:
#for saving
with open("model_pickle","wb") as file:
    pickle.dump(model,file)

In [14]:
# For loading 
with open("model_pickle","rb") as file:
    model_new = pickle.load(file)

In [15]:
model_new.predict([[2600]])

array([533664.38356164])

In [18]:
# for large numpy array we shoule use joblib
import joblib


In [20]:
#for saving
joblib.dump(model,"model_joblib")

['model_joblib']

In [21]:
#for loading
model_new2 = joblib.load('model_joblib')

In [22]:
model_new2.predict([[2600]])

array([533664.38356164])